# Generated by Django 5.1.7 on 2025-03-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
