# Generated by Django 5.1.7 on 2025-03-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_events_from_date_alter_events_to_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='name',
            new_name='team_name',
        ),
        migrations.AddField(
            model_name='entries',
            name='members',
            field=models.TextField(blank=True, null=True),
        ),
    ]
