# Generated by Django 5.1.7 on 2025-03-26 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_name_entries_team_name_entries_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
