# Generated by Django 5.1.7 on 2025-03-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_entries_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='payment_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
