# Generated by Django 5.1.7 on 2025-03-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
