# Generated by Django 5.1.7 on 2025-03-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_events_whatsapp_group_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
