# Generated by Django 5.1.7 on 2025-03-27 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=200, unique=True)),
                ('order_id', models.CharField(max_length=200, unique=True)),
                ('payment_status', models.CharField(max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.entries')),
            ],
        ),
    ]
