# Generated by Django 5.1.7 on 2025-03-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paid_at',
            new_name='payment_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=200),
        ),
    ]
