# Generated by Django 5.1.7 on 2025-03-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_paid_at_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='Mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='entries',
            name='customer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
