# Generated by Django 5.1.7 on 2025-03-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_entries_mobile_alter_entries_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
