# Generated by Django 5.1.7 on 2025-04-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_entries_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='team_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
